permalink:           pretty

# Setup
title:               'JekyllBook'
tagline:             'A Jekyll theme'
url:                 https://madhu-korada.github.io/references/
baseurl:             '/references'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
  name:              Madhu Korada
  url:               https://twitter.com/manoj_korada
github:
  repo:              https://github.com/madhu-korada/

# Custom vars
version:             1.0.0

src:                 "."
default_theme:       "ayu"


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "withmacros"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - README.md

################################### English ####################################
prologues:
  - path: chapters/prologue.md
chapters:
  - path: chapters/python_cpp/title_python_cpp_folder.md
    sections:
      - path: chapters/python_cpp/boost.md
      - path: chapters/python_cpp/cpp.md
      - path: chapters/python_cpp/cuda.md
      - path: chapters/python_cpp/data_manipulation.md
      - path: chapters/python_cpp/keras.md
      - path: chapters/python_cpp/numpy.md
      - path: chapters/python_cpp/opencv.md
      - path: chapters/python_cpp/python.md
      - path: chapters/python_cpp/ros.md
      - path: chapters/python_cpp/serial.md
      - path: chapters/python_cpp/tensorflow.md

  - path: chapters/Linux/title_linux_folder.md
    sections:
      - path: chapters/Linux/cmake.md
      - path: chapters/Linux/docker.md
      - path: chapters/Linux/ffmpeg.md
      - path: chapters/Linux/git.md
      - path: chapters/Linux/linux_commands.md
      - path: chapters/Linux/tmux.md
      - path: chapters/Linux/vim.md
      - path: chapters/Linux/vscode.md

  - path: chapters/extras/title_extras_folder.md
    sections:
      - path: chapters/extras/documentation.md
      - path: chapters/extras/errors.md
      - path: chapters/extras/gps.md
      - path: chapters/extras/installations.md
      - path: chapters/extras/markdown.md

# Chapter Configuration (up to a 2 level nested list)

# prologues:
#   - path: chapters/prologue.md
#     sections:
#       - path: chapters/prologue2.md
# chapters:
#   - path: chapters/01.md
#     sections:
#       - path: chapters/01-1.md
#       - path: chapters/01-2.md
#   - path: chapters/02.md
# epilogues:
#   - path: chapters/epilogue.md


# #epilogues:
# #  - path: chapters/end.md

# # If you want to support multiple languages
# zh:
#   title: 'JekyllBook but in Chinese'
#   tagline: 'A translated Jekyll theme'
#   chapters:
#     - path: zh/01.md
#       sections:
#         - path: zh/01-1.md
#         - path: zh/01-2.md
#     - path: zh/02.md

